# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c146c4985e9e446d867ad96a918fc1b66f596dd2d54e86c9d0b38b02c96adcb3e0ef46f3c26ca730e1314d3c82f58498452b7200cd0c9d3bb38c11865bd302d7

test:
  secret_key_base: fd843b261442a1cda493ff17b2aa8dbb45e4509d6c3facef005e5da0d3577baa59fda4618aa33a90742bd904ed82a5d83aea9aaa2e36c6be2595acdf546b5390

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
